# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
