# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20171229_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
