# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20171229_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.Tournament'),
        ),
    ]
