# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-31 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_matchesscoringrules_matchpoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchesScoringRules',
            new_name='MatchesScoringRule',
        ),
    ]
