# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-31 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20171231_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchPoints',
            new_name='MatchPoint',
        ),
    ]
