# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-31 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20171231_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchesScoringRule',
            new_name='StagesScoringRule',
        ),
    ]
