# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20180119_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_match_predictions', to='tournaments.Team'),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_match_predictions', to='tournaments.Team'),
        ),
    ]
