# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_auto_20180120_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
