# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='first_place_leads_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place_from', to='tournaments.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='second_place_leads_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place_from', to='tournaments.Stage'),
        ),
    ]
