# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_auto_20180303_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
